# Generated by Django 5.1.2 on 2024-11-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField()),
                ('url', models.URLField()),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('scraped_date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
