# Generated by Django 5.1.2 on 2024-11-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_posted',
        ),
    ]
