# Generated by Django 5.1.2 on 2024-11-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='operating_mode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
