# Generated by Django 5.1.2 on 2024-11-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_requested_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested',
            name='title',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
