# Generated by Django 5.1.2 on 2024-11-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_requested_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requested',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
