# Generated by Django 5.1.2 on 2024-11-29 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='scraped_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requested',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requested',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
