# Generated by Django 5.1.2 on 2024-12-24 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-scraped_date']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_date']},
        ),
    ]
